### ISSUE TITLE
TypeError: Path must be a string. Received undefined 

### ISSUE THREAD

**Issue by jrieken** [ChristianKohler/PathIntellisense#11]
from the VS Code error telemetry

```
at Object.getPath (/christian-kohler.path-intellisense-0.2.0/out/src/fs-functions.js:12:19) <no sourcemaps> 
at PathIntellisense.provideCompletionItems (/christian-kohler.path-intellisense-0.2.0/out/src/PathIntellisense.js:13:35) <no sourcemaps> 
at /out/vs/workbench/node/extensionHostProcess.js:17:4899 <no sourcemaps> 
at /out/vs/workbench/node/extensionHostProcess.js:7:12373 <no sourcemaps> 
at new __dirname.undefined.t.Class.derive._oncancel (/out/vs/workbench/node/extensionHostProcess.js:5:17530) <no sourcemaps> 
at Object.c [as asWinJsPromise] (/out/vs/workbench/node/extensionHostProcess.js:7:12338) <no sourcemaps> 
at e.suggest (/out/vs/workbench/node/extensionHostProcess.js:17:4853) <no sourcemaps> 
at /out/vs/workbench/node/extensionHostProcess.js:17:12037 <no sourcemaps> 
```

**Comment by ChristianKohler** [comment]
@jrieken Do you still have this issue?

**Comment by vladamx** [comment]
+1

**Comment by demeter-macik** [comment]
Same issue:

```
shell.ts:428 Path must be a string. Received undefined: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.normalize (path.js:1219:5)
    at Object.getPath (/home/user/.vscode/extensions/christian-kohler.path-intellisense-1.0.2/out/src/fs-functions.js:14:24)
    at PathIntellisense.provideCompletionItems (/home/user/.vscode/extensions/christian-kohler.path-intellisense-1.0.2/out/src/PathIntellisense.js:15:35)
    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:12:2357
    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:6:22775
    at new n.Class.derive._oncancel (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:5:26897)
    at Object.l [as asWinJsPromise] (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:6:22738)
    at e.provideCompletionItems (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:12:2311)
    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:12:9826
```
- node -v: v4.4.5
- npm -v: 2.15.5
- VSCode Version: Code 1.5.3
- OS Version: Linux x64 4.2.0-42-generic

**Comment by orta** [comment]
Hello there, I set a breakpoint on the error message in the electron shell, this occurred as I was writing a comment in a js file, will see if I can add debugging tools inside the extension to find out what's getting passed around

![screen shot 2016-09-28 at 09 39 09](https://cloud.githubusercontent.com/assets/49038/18906478/9a4ce002-855f-11e6-93fa-ab132f09e17a.png)

**Comment by octref** [comment]
This issue still persists in VSCode 1.6 with Path Intellisense 1.0.2.

If I'm typing anything not starting with dot it throws this error

![image](https://cloud.githubusercontent.com/assets/4033249/18964502/05174e80-862e-11e6-8b87-d9d8721b2fc3.png)

And I'd avoid doing `console.log` like this: https://github.com/ChristianKohler/PathIntellisense/blob/3b61969973b7cfae3a44bd4f9dae7d5073cb762b/src/fs-functions.ts#L13-L20

Better to just set a breakpoint and watch for variables, if you are doing them for the sake of debugging.
