### ISSUE TITLE
Error: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by obrejla** [ChristianKohler/PathIntellisense#56]
Hi,
I saw this in CDT console output. Not sure how it happened, sorry :(
```
//Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:142 Cannot read property 'indexOf' of undefined: TypeError: Cannot read property 'indexOf' of undefined
    at /Users/ondrejbrejla/.vscode/extensions/christian-kohler.path-intellisense-1.2.0/out/src/PathIntellisense.js:27:110
    at Array.some (native)
    at PathIntellisense.shouldProvide (/Users/ondrejbrejla/.vscode/extensions/christian-kohler.path-intellisense-1.2.0/out/src/PathIntellisense.js:27:55)
    at PathIntellisense.provideCompletionItems (/Users/ondrejbrejla/.vscode/extensions/christian-kohler.path-intellisense-1.2.0/out/src/PathIntellisense.js:22:21)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:14:11877
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:17664
    at new n.Class.derive._oncancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:13768)
    at Object.h [as asWinJsPromise] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:6:17627)
    at e.provideCompletionItems (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:14:11831)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:14:21033
```
Thanks!

**Comment by ChristianKohler** [comment]
Thank you @obrejla. I could fix that bug with the output you provided
