### ISSUE TITLE
Activating extension failed

### ISSUE THREAD

**Issue by minedeljkovic** [ChristianKohler/PathIntellisense#66]
Seems like 1.3.0 regression.

From VSCode developer tools console:
`Activating extension `christian-kohler.path-intellisense` failed: Cannot find module '../utils/config'`
```
[Extension Host] Here is the error stack:  Error: Cannot find module '../utils/config'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Function.J.i._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:374834)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/saga/.vscode/extensions/christian-kohler.path-intellisense-1.3.0/out/src/completionItems/UpCompletionItem.js:14:16)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.J.i._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:374834)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/saga/.vscode/extensions/christian-kohler.path-intellisense-1.3.0/out/src/PathIntellisense.js:7:26)
    at Module._compile (module.js:556:32)
```

Edit: added stack trace

**Comment by teamsteamdev** [comment]
Same error with 1.4.0. Here's my stack trace: 

```
[Extension Host] Here is the error stack:  Error: Cannot find module '../utils/config'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Function.Y.o._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:366384)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/teamsteamnm/.vscode/extensions/christian-kohler.path-intellisense-1.4.0/out/src/completionItems/UpCompletionItem.js:14:16)
    at Object.<anonymous> (/home/teamsteamnm/.vscode/extensions/christian-kohler.path-intellisense-1.4.0/out/src/completionItems/UpCompletionItem.js:26:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.Y.o._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:366384)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/teamsteamnm/.vscode/extensions/christian-kohler.path-intellisense-1.4.0/out/src/PathIntellisense.js:7:26)
```

**Comment by ChristianKohler** [comment]
@minedeljkovic @teamsteamdev It seems that the out folder was not properly cleaned before the last build. I created a new build (1.4.1) with a cleaned out folder but without any code changes. Could you try whether this solves the issue? Thank you.

**Comment by teamsteamdev** [comment]
Looks good!

**Comment by ChristianKohler** [comment]
@teamsteamdev Thank you.
