### ISSUE TITLE
Errors in dev console

### ISSUE THREAD

**Issue by jtsom** [ChristianKohler/PathIntellisense#91]
Seeing this error in the dev console in VS Code Insiders (latest):
```
[Extension Host] SyntaxError: Unexpected token / in JSON at position 887
	at JSON.parse (<anonymous>)
	at C:\Users\John Tsombakos\.vscode-insiders\extensions\christian-kohler.path-intellisense-1.4.2\out\src\utils\config.js:20:25
	at Object.m [as _notify] (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:43556)
	at Object.enter (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:47121)
	at n.Class.derive._oncancel._run (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:48949)
	at n.Class.derive._oncancel._completed (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:48390)
	at e.resolveOk (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:282072)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:283579)
	at c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:282891
	at c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:284810
```

**Comment by jtsom** [comment]
N/M.... was a syntax error in the tsconfig.json file
