### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by Zerogiven** [ChristianKohler/PathIntellisense#99]
- Extension Name: path-intellisense
- Extension Version: 1.4.2
- OS Version: Linux x64 4.13.0-26-generic
- VSCode version: 1.19.2

```bash
```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 9,
		"activateCallTime": 2,
		"activateResolvedTime": 0,
		"activationEvent": "*"
	},
	"runtimeErrors": [
		{
			"name": "SyntaxError",
			"message": "Unexpected token / in JSON at position 25"
		}
	]
}
```
```

**Comment by Zerogiven** [comment]
Some more info from the dev tools console


/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4056 SyntaxError: Unexpected token / in JSON at position 25
	at JSON.parse (<anonymous>)
	at /home/csoellinger/.vscode/extensions/christian-kohler.path-intellisense-1.4.2/out/src/utils/config.js:20:25
	at Object.g [as _notify] (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:67:449)
	at Object.enter (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:70:778)
	at n.Class.derive._oncancel._run (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:72:573)
	at n.Class.derive._oncancel._completed (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:72:14)
	at e.resolveOk (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:355:384)
	at e._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:356:894)
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:356:206
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:358:204
e.$onExtensionRuntimeError @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4056
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] WARNING: Promise with no error callback:2
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host]% Objecterror: nullexception: Object__proto__: Objectid: 2promise: Object_creator: null_errorId: 2_isException: true_listeners: null_nextState: null_state: Object_value: Object__proto__: Object__proto__: Object__proto__: Object
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:249 [Extension Host] SyntaxError: Unexpected token / in JSON at position 25
	at JSON.parse (<anonymous>)
	at /home/csoellinger/.vscode/extensions/christian-kohler.path-intellisense-1.4.2/out/src/utils/config.js:20:25
	at Object.g [as _notify] (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:67:449)
	at Object.enter (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:70:778)
	at n.Class.derive._oncancel._run (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:72:573)
	at n.Class.derive._oncancel._completed (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:72:14)
	at e.resolveOk (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:355:384)
	at e._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:356:894)
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:356:206
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:358:204

**Comment by tonyhallett** [comment]
This is probably due to comments in your tsconfig.  tsconfig -init produces tsconfig.json with commented out options.  Comments in json are an extension to the JSON specification and so the extension code will throw when JSON.parse is called on the contents of your tsconfig.json.

**Comment by tonyhallett** [comment]
This has been addressed by the pull request https://github.com/ChristianKohler/PathIntellisense/pull/82. https://github.com/ChristianKohler/PathIntellisense/pull/82/commits/133f1c6692d64b096eeb10b396887b9015095b15
